name: Build-Service
description: Build a service application of CTMD-Dashboard
inputs:
  app-name:
    description: Name of application to build
    required: true
  tag:
    description: Tag to use for build 
    required: true
  release-tag:
    description: Tag for release 
    required: false
  docker-name:
    description: Name for docker login 
    required: true 
  docker-token:
    description: Docker token for login 
    required: true 
  container-name:
    description: Login name
    required: true 
  container-token:
    description: Login token
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    # Necessary to use make to build the image and send the cache off
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: containers.renci.org
        username: ${{ secrets.CONTAINERHUB_USERNAME }}
        password: ${{ secrets.CONTAINERHUB_TOKEN }}
        logout: true
    - name: Build Api
      uses: docker/build-push-action@v6
      with:
        context: ./services/${{ inputs.app-name }}/
        file: ./services/${{ inputs.app-name }}/Dockerfile
        push: true
        tags: |
          containers.renci.org/ctmd/ctmd-${{ inputs.app-name }}:{{ inputs.tag }}
          rencibuild/ctmd-${{ inputs.app-name }}:${{ inputs.tag }}
        cache-from: type=registry,ref=rencibuild/ctmd-${{ inputs.app-name }}:buildcache
        cache-to: type=registry,ref=rencibuild/ctmd-${{ inputs.app-name }}:buildcache,mode=max