name: Build-Pipeline
on:
    push:
     branches-ignore:
      - master
      - main
      - develop
     paths:
     - services/pipeline/**
    workflow_dispatch:  
jobs:
  build-push-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    # Necessary to use make to build the image and send the cache off
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: containers.renci.org
        username: ${{ secrets.CONTAINERHUB_USERNAME }}
        password: ${{ secrets.CONTAINERHUB_TOKEN }}
        logout: true

    - name: Parse Github Reference Name
      id: branch
      run: |
        REF=${{ github.ref_name }}
        echo "GHR=${REF%/*}" >> $GITHUB_OUTPUT

    - name: Build Server Container for Appstore-Sockets
      uses: docker/build-push-action@v6
      with:
        context: ./services/pipeline/
        file: ./services/pipeline/patch.Dockerfile
        push: true
        tags: |
          containers.renci.org/ctmd/ctmd-pipeline:test_${{ steps.branch.outputs.GHR }}
          rencibuild/ctmd-pipeline:test_${{ steps.branch.outputs.GHR }}
        cache-from: type=registry,ref=rencibuild/ctmd-pipeline:buildcache
        cache-to: type=registry,ref=rencibuild/ctmd-pipeline:buildcache,mode=max