name: Build-Api
on:
    # On demand build of the application if necessary
    workflow_dispatch:
      
    push:
      branches-ignore:
      - main 
      - master
      paths:
      - services/api/**
      - .github/**
      tags-ignore:
      - '*'

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-${{ github.workflow }}-buildapi
  cancel-in-progress: true  

jobs:
  build-push-api:
    runs-on: ubuntu-latest
    steps:
    
    # Obtain the branch being developed
    - name: Set branch name
      id: branch
      run: |
        REF=${{ github.ref_name }}
        echo "GHR=${REF%/*}" >> $GITHUB_ENV

    - uses: ./github/actions/build-service
      with:
        app-name: 'api'
        tag: 'test_${{ env.GHR }}'