name: Build-Pipeline
on:
    push:
     branches-ignore:
      - master
      - main
      - develop
     paths:
     - services/pipeline/**
     tags-ignore:
     - '*'
    workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-${{ github.workflow }}-buildpipe
  cancel-in-progress: true   

jobs:
  build-push-api:
    runs-on: ubuntu-latest
    steps:
    
    # Obtain the branch being developed
    - name: Set branch name
      id: branch
      run: |
        REF=${{ github.ref_name }}
        echo "GHR=${REF%/*}" >> $GITHUB_ENV

    - uses: ./.github/actions/build-service
      with:
        app-name: 'pipeline'
        tag: 'test_${{ env.GHR }}'