name: Build-Pipeline
on:
    push:
     branches-ignore:
      - master
      - main
      - develop
     paths:
     - services/pipeline/**
     - .github/**
     - Makefile
jobs:
  build-push-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    # Necessary to use make to build the image and send the cache off
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host
        daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

    - name: Docker Login Dockerhub (Redundancy)
      run: | 
        docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
 
    - name: Build Pipeline
      run: | 
        make build-pipeline-cicd

    - name: Logout Dockerhub 
      run: | 
        docker logout 

    - name: Docker Login to Containers
      run: |
        docker login containers.renci.org --username ${{ secrets.CONTAINERHUB_USERNAME }} --password ${{ secrets.CONTAINERHUB_TOKEN }}
    
    - name: Push Pipeline to Containers
      run: | 
        make push-pipeline

    - name: Logout of Containers
      run: |
        docker logout containers.renci.org
