name: trivy-pr-scan
on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize ]
    paths-ignore:
    - README.md
    - README.md.old
    - .github/**
    - LICENSE
    - .gitignore
    - .dockerignore
    - .githooks 

jobs:
 trivy-pr-scan:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

